// Real local backend + Next.js; model and external action are simulated by the
// explicit Python fixture driver. Never point this script at production.
const {chromium} = require('playwright');
const {execFileSync} = require('node:child_process');
const assert = require('node:assert/strict');
const path = require('node:path');
const root = path.resolve(__dirname, '../..');
const driver = action => execFileSync(path.join(root,'.venv/bin/python'), [path.join(root,'tests/e2e/bounded_fixture.py'), action], {cwd:root, encoding:'utf8'});
(async () => {
  driver('seed');
  const browser = await chromium.launch({headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1050}});
  page.setDefaultTimeout(30000);
  const errors=[]; page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://localhost:13201/login');
  await page.fill('#signin-email',process.env.USER_NAME);
  await page.fill('#signin-password',process.env.PASSWORD);
  await page.fill('#setup-token',process.env.LOMA_SETUP_TOKEN);
  await page.waitForLoadState('networkidle');
  await page.waitForTimeout(500);
  await page.click('button[type=submit]');
  await page.waitForURL(u => !u.pathname.includes('/login'));
  await page.goto('http://localhost:13201/agents/work');
  await page.getByRole('button',{name:'New work',exact:true}).click();
  const form = page.getByRole('dialog',{name:'Give an agent a job'});
  await form.locator('#agent').selectOption('bounded-qa');
  await form.locator('#job-title').fill('Invoice follow-up QA');
  await form.locator('#instructions').fill('Review the test invoice and propose a reminder.');
  await form.locator('#success').fill('An exact reminder and its simulated receipt.');
  await form.locator('#recipients').fill('recipient@example.com');
  // Simulate a save failure and ensure inputs survive, then submit for real.
  await page.route('**/work-api/work', route => route.fulfill({status:503,json:{error:'Temporary test failure. Try again.'}}), {times:1});
  await form.getByRole('button',{name:'Save paused work'}).click();
  await form.getByRole('alert').waitFor();
  assert.equal(await form.locator('#job-title').inputValue(),'Invoice follow-up QA');
  await form.getByRole('button',{name:'Save paused work'}).click();
  await form.waitFor({state:'hidden'});
  const card = page.getByRole('region',{name:'Invoice follow-up QA'});
  await card.getByRole('button',{name:'Safe test',exact:true}).click();
  driver('step'); await page.reload();
  await page.getByRole('button',{name:'Run history',exact:true}).click();
  await page.getByRole('button',{name:/Invoice follow-up QA · Safe test/}).waitFor();
  await page.getByRole('button',{name:'Work',exact:true}).click();
  await card.getByRole('button',{name:'Add schedule',exact:true}).click();
  const scheduling = page.getByRole('dialog',{name:'Add a schedule'});
  await scheduling.getByRole('button',{name:'Save paused schedule'}).click();
  await scheduling.waitFor({state:'hidden'});
  await card.getByRole('button',{name:'Enable work',exact:true}).click();
  await card.getByRole('button',{name:'Run now',exact:true}).waitFor();
  driver('schedule');
  driver('step'); await page.reload();
  await page.getByRole('button',{name:'Needs you (1)',exact:true}).click();
  await page.getByRole('button',{name:'Review exact action'}).click();
  const review = page.getByRole('dialog',{name:'Review before authorizing'});
  assert.match(await review.innerText(),/recipient@example.com/);
  assert.match(await review.innerText(),/local test proposal/);
  await page.screenshot({path:'/tmp/bounded-approval-desktop.png'});
  await review.getByRole('button',{name:'Edit proposal'}).click();
  await review.locator('#review-body').fill('Edited QA reminder. This exact text is authorized.');
  await review.getByRole('button',{name:'Save new version'}).click();
  await review.waitFor({state:'hidden'});
  await page.getByRole('button',{name:'Review exact action'}).click();
  assert.match(await review.innerText(),/Version 2/);
  await page.setViewportSize({width:390,height:844});
  assert(await review.evaluate(e => e.scrollWidth <= e.clientWidth + 1));
  await page.screenshot({path:'/tmp/bounded-approval-mobile.png'});
  await review.getByRole('button',{name:'Approve & send'}).focus();
  await page.keyboard.press('Enter');
  await review.waitFor({state:'hidden'});
  driver('step'); await page.reload();
  await page.getByRole('button',{name:'Run history',exact:true}).click();
  await page.getByText('✋ gmail.send · executed',{exact:true}).waitFor();
  await page.getByText('✋ gmail.send · executed',{exact:true}).click();
  assert.match(await page.innerText('main'),/SIMULATED-RECEIPT-NOT-SENT/);
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  await page.screenshot({path:'/tmp/bounded-history-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Work',exact:true}).click();
  await card.getByRole('button',{name:'Knowledge & memory'}).click();
  const notes = page.getByRole('dialog',{name:'Knowledge & memory'});
  await notes.locator('#note-title').fill('Approved invoice context');
  await notes.locator('#note-content').fill('Use a courteous tone. Test data only.');
  await notes.getByRole('button',{name:'Save note',exact:true}).click();
  await notes.getByRole('button',{name:'Approved invoice context'}).click();
  await notes.locator('#note-content').fill('Updated context');
  await notes.getByRole('button',{name:'Update note'}).click();
  await notes.getByRole('button',{name:'Delete',exact:true}).click();
  await notes.getByRole('button',{name:'Approved invoice context'}).waitFor({state:'hidden'});
  await notes.getByRole('button',{name:'Save note',exact:true}).waitFor();
  await page.waitForFunction(() => !document.querySelector('[role=dialog] button[type=submit]')?.disabled);
  await notes.getByRole('button',{name:'Close',exact:true}).click();
  await notes.waitFor({state:'hidden'});
  await page.setViewportSize({width:1440,height:1050});
  await page.screenshot({path:'/tmp/bounded-work-desktop.png',fullPage:true});
  await card.getByRole('button',{name:'Edit schedule',exact:true}).click();
  const editSchedule = page.getByRole('dialog',{name:'Edit schedule',exact:true});
  await editSchedule.locator('#cron').fill('0 10 * * 1-5');
  await editSchedule.getByRole('button',{name:'Save paused schedule'}).click();
  await editSchedule.waitFor({state:'hidden'});
  await card.getByRole('button',{name:'Enable work',exact:true}).waitFor();
  assert.match(await card.innerText(), /0 10 \* \* 1-5/);
  driver('verify');
  assert.deepEqual(errors,[]);
  console.log('PASS: create/error preservation, dry run, enable, proposal, edit/version, keyboard approve, receipt, notes CRUD, desktop/mobile overflow. No external send.');
  await browser.close();
})().catch(e => {console.error(e);process.exit(1);});
