// Real local backend + Next.js; model and external action are simulated by the
// explicit Python fixture driver. Never point this script at production.
const {chromium} = require('playwright');
const {execFileSync} = require('node:child_process');
const assert = require('node:assert/strict');
const path = require('node:path');
const root = path.resolve(__dirname, '../..');
const driver = action => execFileSync(path.join(root,'.venv/bin/python'), [path.join(root,'tests/e2e/bounded_fixture.py'), action], {cwd:root, encoding:'utf8'});
(async () => {
  driver('seed');
  const browser = await chromium.launch({headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1050}});
  page.setDefaultTimeout(30000);
  const errors=[]; page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://localhost:13201/login');
  await page.fill('#signin-email',process.env.USER_NAME);
  await page.fill('#signin-password',process.env.PASSWORD);
  await page.fill('#setup-token',process.env.LOMA_SETUP_TOKEN);
  await page.waitForLoadState('networkidle');
  await page.waitForTimeout(500);
  await page.click('button[type=submit]');
  await page.waitForURL(u => !u.pathname.includes('/login'));
  await page.goto('http://localhost:13201/agents/work');
  await page.getByRole('button',{name:'New work',exact:true}).click();
  const form = page.getByRole('dialog',{name:'Give an agent a job'});
  await form.locator('#agent').selectOption('bounded-qa');
  await form.locator('#job-title').fill('Invoice follow-up QA');
  await form.locator('#instructions').fill('Review the test invoice and propose a reminder.');
  await form.locator('#success').fill('An exact reminder and its simulated receipt.');
  await form.locator('#recipients').fill('recipient@example.com');
  await form.locator('[id="gmail.search"]').selectOption('allow');
  await form.locator('[id="gmail.read"]').selectOption('allow');
  await form.locator('#cost-budget').fill('2.50');
  await form.locator('#runtime').fill('120');
  await form.locator('#retries').selectOption('1');
  await page.setViewportSize({width:390,height:844});
  await form.locator('#runtime').scrollIntoViewIfNeeded();
  assert(await form.evaluate(e => e.scrollWidth <= e.clientWidth + 1));
  await page.screenshot({path:'/tmp/bounded-limits-mobile.png'});
  await page.setViewportSize({width:1440,height:1050});
  // Simulate a save failure and ensure inputs survive, then submit for real.
  await page.route('**/work-api/work', route => route.fulfill({status:503,json:{error:'Temporary test failure. Try again.'}}), {times:1});
  await form.getByRole('button',{name:'Save paused work'}).click();
  await form.getByRole('alert').waitFor();
  assert.equal(await form.locator('#job-title').inputValue(),'Invoice follow-up QA');
  assert.equal(await form.locator('#runtime').inputValue(),'120');
  assert.equal(await form.locator('#retries').inputValue(),'1');
  assert.equal(await form.locator('#cost-budget').inputValue(),'2.50');
  await form.getByRole('button',{name:'Save paused work'}).click();
  await form.waitFor({state:'hidden'});
  const card = page.getByRole('region',{name:'Invoice follow-up QA'});
  assert.match(await card.innerText(), /120 minute deadline · 1 model retry/);
  assert.match(await card.innerText(), /\$2.50 model budget/);
  await card.getByRole('button',{name:'Safe test',exact:true}).click();
  driver('step'); await page.reload();
  await page.getByRole('button',{name:'Run history',exact:true}).click();
  await page.getByRole('button',{name:/Invoice follow-up QA · Safe test/}).waitFor();
  await page.getByRole('button',{name:'Work',exact:true}).click();
  await card.getByRole('button',{name:'Add schedule',exact:true}).click();
  const scheduling = page.getByRole('dialog',{name:'Add a schedule'});
  await scheduling.getByRole('button',{name:'Save paused schedule'}).click();
  await scheduling.waitFor({state:'hidden'});
  await card.getByRole('button',{name:'Enable work',exact:true}).click();
  await card.getByRole('button',{name:'Run now',exact:true}).waitFor();
  driver('schedule');
  driver('step'); await page.reload();
  await page.getByRole('button',{name:'Needs you (1)',exact:true}).click();
  await page.getByRole('button',{name:'Review exact action'}).click();
  const review = page.getByRole('dialog',{name:'Review before authorizing'});
  assert.match(await review.innerText(),/recipient@example.com/);
  assert.match(await review.innerText(),/local test proposal/);
  await page.screenshot({path:'/tmp/bounded-approval-desktop.png'});
  await review.getByRole('button',{name:'Edit proposal'}).click();
  await review.locator('#review-body').fill('Edited QA reminder. This exact text is authorized.');
  await review.getByRole('button',{name:'Save new version'}).click();
  await review.waitFor({state:'hidden'});
  await page.getByRole('button',{name:'Review exact action'}).click();
  assert.match(await review.innerText(),/Version 2/);
  await page.setViewportSize({width:390,height:844});
  assert(await review.evaluate(e => e.scrollWidth <= e.clientWidth + 1));
  await page.screenshot({path:'/tmp/bounded-approval-mobile.png'});
  await review.getByRole('button',{name:'Approve & send'}).focus();
  await page.keyboard.press('Enter');
  await review.waitFor({state:'hidden'});
  driver('step'); await page.reload();
  await page.getByRole('button',{name:'Run history',exact:true}).click();
  await page.getByText('✋ gmail.send · executed',{exact:true}).waitFor();
  await page.getByText('✋ gmail.send · executed',{exact:true}).click();
  assert.match(await page.innerText('main'),/SIMULATED-RECEIPT-NOT-SENT/);
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  await page.screenshot({path:'/tmp/bounded-history-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Work',exact:true}).click();
  await card.getByRole('button',{name:'Knowledge & memory'}).click();
  const notes = page.getByRole('dialog',{name:'Knowledge & memory'});
  await notes.locator('#note-title').fill('Approved invoice context');
  await notes.locator('#note-content').fill('Use a courteous tone. Test data only.');
  await notes.getByRole('button',{name:'Save note',exact:true}).click();
  await notes.getByRole('button',{name:'Approved invoice context'}).click();
  await notes.locator('#note-content').fill('Updated context');
  await notes.getByRole('button',{name:'Update note'}).click();
  await notes.getByRole('button',{name:'Delete',exact:true}).click();
  await notes.getByRole('button',{name:'Approved invoice context'}).waitFor({state:'hidden'});
  await notes.getByRole('button',{name:'Save note',exact:true}).waitFor();
  await page.waitForFunction(() => !document.querySelector('[role=dialog] button[type=submit]')?.disabled);
  await notes.getByRole('button',{name:'Close',exact:true}).click();
  await notes.waitFor({state:'hidden'});
  await page.setViewportSize({width:1440,height:1050});
  await page.screenshot({path:'/tmp/bounded-work-desktop.png',fullPage:true});
  await card.getByRole('button',{name:'Edit schedule',exact:true}).click();
  const editSchedule = page.getByRole('dialog',{name:'Edit schedule',exact:true});
  await editSchedule.locator('#cron').fill('0 10 * * 1-5');
  await editSchedule.getByRole('button',{name:'Save paused schedule'}).click();
  await editSchedule.waitFor({state:'hidden'});
  await card.getByRole('button',{name:'Enable work',exact:true}).waitFor();
  assert.match(await card.innerText(), /0 10 \* \* 1-5/);
  driver('verify');
  await card.getByRole('button',{name:'Safe test',exact:true}).click();
  driver('expire'); await page.reload();
  await card.getByRole('button',{name:'Latest: failed (safe test)',exact:true}).click();
  const expiredRun = page.getByRole('dialog',{name:'Invoice follow-up QA',exact:true});
  assert.match(await expiredRun.innerText(), /Run deadline reached/);
  assert.match(await expiredRun.innerText(), /Deadline:/);
  assert.match(await expiredRun.innerText(), /No further wake-ups/);
  assert.doesNotMatch(await expiredRun.innerText(), /Next eligible wake/);
  assert.equal(await expiredRun.getByRole('button',{name:'Stop this run and delegates'}).count(),0);
  await page.setViewportSize({width:390,height:844});
  assert(await expiredRun.evaluate(e => e.scrollWidth <= e.clientWidth + 1));
  await page.screenshot({path:'/tmp/bounded-deadline-mobile.png'});
  await expiredRun.getByRole('button',{name:'Close',exact:true}).click();
  driver('uncertain'); await page.reload();
  await page.getByRole('button',{name:'Needs you (1)',exact:true}).click();
  await page.getByText('Delivery review · Not an approval',{exact:false}).waitFor();
  await page.getByRole('button',{name:'Investigate delivery',exact:true}).click();
  const investigation = page.getByRole('dialog',{name:'Investigate email delivery',exact:true});
  assert.match(await investigation.innerText(),/does not send an email/);
  const saveInvestigation = investigation.getByRole('button',{name:'Record investigation',exact:true});
  assert(await saveInvestigation.isDisabled());
  await investigation.locator('#delivery-outcome').selectOption('unknown');
  await investigation.locator('#delivery-evidence').fill('No conclusive provider evidence yet. Synthetic QA.');
  assert(await saveInvestigation.isDisabled());
  await investigation.getByRole('checkbox').check();
  await page.route('**/work-api/approvals/*/reconcile', route => route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Simulated save failure. Your notes are preserved.'})}), {times:1});
  await saveInvestigation.click();
  await investigation.getByRole('alert').waitFor();
  assert.equal(await investigation.locator('#delivery-evidence').inputValue(),'No conclusive provider evidence yet. Synthetic QA.');
  assert(await investigation.getByRole('checkbox').isChecked());
  await saveInvestigation.focus(); await page.keyboard.press('Enter');
  await investigation.waitFor({state:'hidden'});
  await page.getByRole('button',{name:'Needs you (1)',exact:true}).waitFor();
  await page.getByRole('button',{name:'Investigate delivery',exact:true}).click();
  await investigation.locator('#delivery-outcome').selectOption('sent');
  await investigation.locator('#delivery-evidence').fill('Synthetic owner report: matching message ID QA-123, recipient and exact body verified. No live provider contacted.');
  await investigation.getByRole('checkbox').check();
  assert(await investigation.evaluate(e => e.scrollWidth <= e.clientWidth + 1));
  await page.screenshot({path:'/tmp/bounded-investigation-mobile.png'});
  await page.setViewportSize({width:1440,height:1050});
  await page.waitForTimeout(600);
  await page.screenshot({path:'/tmp/bounded-investigation-desktop.png'});
  await saveInvestigation.focus(); await page.keyboard.press('Enter');
  await investigation.waitFor({state:'hidden'});
  await page.getByRole('button',{name:'Needs you (0)',exact:true}).waitFor();
  await page.getByRole('button',{name:'Run history',exact:true}).click();
  await page.getByText('✋ gmail.send · Outcome unknown',{exact:true}).click();
  await page.getByText('Owner report: sent.',{exact:false}).waitFor();
  await page.getByRole('button',{name:'Review investigation',exact:true}).click();
  await investigation.getByText('Previous investigation notes (2)',{exact:true}).click();
  assert.match(await investigation.innerText(),/No conclusive provider evidence yet/);
  assert.match(await investigation.innerText(),/QA-123/);
  await investigation.getByRole('button',{name:'Cancel',exact:true}).click();
  driver('verify-investigation');
  driver('provider-check'); await page.reload();
  await page.getByRole('button',{name:'Run history',exact:true}).click();
  await page.getByText('✋ gmail.send · Verified in Gmail Sent',{exact:true}).click();
  const verification = page.getByRole('region',{name:'Gmail verification',exact:true});
  await verification.waitFor();
  assert.match(await verification.innerText(), /Verified in Gmail Sent/);
  assert.match(await verification.innerText(), /does not confirm recipient delivery/);
  assert.match(await verification.innerText(), /SIMULATED-GMAIL-MATCH/);
  await page.setViewportSize({width:1440,height:1050});
  await verification.scrollIntoViewIfNeeded();
  await page.screenshot({path:'/tmp/bounded-provider-desktop.png'});
  await page.setViewportSize({width:390,height:844});
  await verification.scrollIntoViewIfNeeded();
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  await page.screenshot({path:'/tmp/bounded-provider-mobile.png'});
  driver('costs'); await page.reload();
  await page.getByRole('button',{name:'Run history',exact:true}).click();
  await page.getByRole('button',{name:/Invoice follow-up QA · Safe test/}).first().click();
  const costs = page.getByRole('region',{name:'Model budget',exact:true});
  await costs.waitFor();
  assert.match(await costs.innerText(), /Shared run budget: \$2.50/);
  assert.match(await costs.innerText(), /\$0.0045 recorded/);
  assert.match(await costs.innerText(), /1?000 input/);
  assert.match(await costs.innerText(), /billing outcome is unknown/);
  await page.setViewportSize({width:1440,height:1050});
  await page.waitForTimeout(500);
  await page.screenshot({path:'/tmp/bounded-cost-desktop.png'});
  await page.setViewportSize({width:390,height:844});
  await costs.scrollIntoViewIfNeeded();
  await page.waitForTimeout(500);
  assert(await page.getByRole('dialog').evaluate(e => e.scrollWidth <= e.clientWidth + 1));
  await page.screenshot({path:'/tmp/bounded-cost-mobile.png'});
  assert.deepEqual(errors,[]);
  console.log('PASS: create/error preservation, dry run, enable, proposal, edit/version, keyboard approve, receipt, notes CRUD, deadline expiry, limit persistence, delivery investigation/error preservation/corrections, no resend or resume, desktop/mobile overflow. No external send.');
  await browser.close();
})().catch(e => {console.error(e);process.exit(1);});
