"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { api } from "@/lib/bounded-work-api";
import { KnowledgeLibrary, type Source } from "./KnowledgeLibrary";
import { basePath } from "@/lib/api";
import { fetchAgentIdentities, type AgentIdentity } from "@/lib/agents-api";
import { useUser } from "@/lib/UserContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";

type Mode = "allow" | "ask" | "deny";
type Policy = { actions: Record<string, Mode>; recipients: string[]; channels?: string[] };
type Work = { knowledge_ids?: string[]; work_id: string; title: string; agent_id: string; owner: string; instructions: string; success: string; paused: boolean; revoked?: boolean; max_steps: number; max_runtime_minutes?: number; max_planner_retries?: number; max_cost_microusd?: number; policy: Policy; cron?: string; timezone?: string; flow_id?: string; next_run_at?: string; schedule_error?: string };
type Cost = { cost_committed_nusd?: number; cost_recorded_nusd?: number; input_tokens_used?: number; output_tokens_used?: number; max_cost_microusd?: number };
const usd = (nanos: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 2, maximumFractionDigits: 4 }).format(nanos / 1e9);
function CostSummary({ run }: { run: Run }) {
  const cost = run.shared_cost || run;
  const cap = run.shared_cost?.max_cost_microusd ?? run.snapshot?.max_cost_microusd ?? 1000000;
  const held = Math.max(0, (cost.cost_committed_nusd || 0) - (cost.cost_recorded_nusd || 0));
  return <section aria-label="Model budget" className="rounded-lg border p-3 text-sm space-y-1"><p className="font-medium">{run.parent_id ? "Shared with parent and delegates" : "Shared run budget"}: {usd(cap * 1000)}</p><p>{usd(cost.cost_recorded_nusd || 0)} recorded · {usd(held)} reserved</p>{held > 0 && <p className="text-xs text-muted-foreground">Reserved is not confirmed spend. A call may still be running, or its billing outcome is unknown. These funds cannot be reused.</p>}<p className="text-xs text-muted-foreground">{cost.input_tokens_used || 0} input / {cost.output_tokens_used || 0} output tokens reported. Calculated using configured price ceilings, not your provider invoice. Connector charges excluded.</p></section>;
}
type CostEntry = { reservation_id: string; status: string; reserved_nusd?: number; actual_nusd?: number };
type CostReview = { outcome: string; notes: string; actor: string; at: string; version: number };
type Run = Cost & { snapshot?: { max_cost_microusd?: number }; shared_cost?: Cost; run_id: string; work_id: string; status: string; dry_run: boolean; step: number; max_steps: number; calls_used: number; deadline_at?: string; planner_retries?: number; result: string; question?: string; wake_at: string; parent_id?: string; history: Record<string, unknown>[]; cost_ledger?: CostEntry[]; cost_review?: CostReview; cost_review_history?: CostReview[]; event_note?: string };
type Approval = { approval_id: string; work_id: string; run_id: string; action: string; args: Record<string,string>; reason: string; owner: string; status: string; version: number; expires_at: string; receipt?: unknown; digest: string; provider_check?: {outcome?: string; checked_at?: string; attempts?: number; message_id?: string}; provider_message_id?: string; reconciliation?: { outcome: string; evidence: string; actor: string; at: string; version: number }; reconciliation_history?: { outcome: string; evidence: string; actor: string; at: string; version: number }[] };
type Note = { note_id: string; title: string; content: string };
type Overview = { attention_limited?: boolean; work: Work[]; runs: Run[]; approvals: Approval[]; model_ready: boolean; pricing_ready?: boolean; google_connected: boolean; slack_connected?: boolean; worker_enabled: boolean };
const actions = { "gmail.search": "Search my Gmail", "gmail.read": "Read my Gmail", "gmail.send": "Send email", "slack.send": "Send Slack message", "calendar.list": "Read my upcoming calendar events" };
const writeActions = ["gmail.send", "slack.send"];
const select = "h-10 w-full rounded-md border bg-background px-3 text-sm";
const initialPolicy: Policy = { actions: { "gmail.search": "deny", "gmail.read": "deny", "gmail.send": "ask", "slack.send": "deny", "calendar.list": "deny" }, recipients: [], channels: [] };
const heldFor = (run: Run) => (run.cost_ledger || []).some(e => e.status === "held");
const chargeUnresolved = (run: Run) => !run.parent_id && ["done", "failed", "cancelled"].includes(run.status) && heldFor(run) && !["billed", "not_billed"].includes(run.cost_review?.outcome || "");
const statusLabel = (status: string) => ({ waiting_approval: "Needs approval", needs_input: "Needs your input", waiting_child: "Waiting for delegate", queued: "Waiting to wake", executing: "Executing", uncertain: "Outcome unknown", preview: "Preview only" }[status] || status.replaceAll("_", " "));


export default function AgentWorkPage() {
  const { user } = useUser();
  const [data, setData] = useState<Overview | null>(null);
  const [agents, setAgents] = useState<AgentIdentity[]>([]);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState("");
  const [tab, setTab] = useState("work");
  const [library, setLibrary] = useState(false);
  const [sources, setSources] = useState<Source[]>([]);
  const [knowledgeIds, setKnowledgeIds] = useState<string[]>([]);
  const [creating, setCreating] = useState(false);
  const [title, setTitle] = useState("");
  const [agentId, setAgentId] = useState("");
  const [instructions, setInstructions] = useState("");
  const [success, setSuccess] = useState("");
  const [policy, setPolicy] = useState<Policy>(initialPolicy);
  const [recipients, setRecipients] = useState("");
  const [channels, setChannels] = useState("");
  const [delegates, setDelegates] = useState<string[]>([]);
  const [budget, setBudget] = useState(10);
  const [costBudget, setCostBudget] = useState("1.00");
  const [runtime, setRuntime] = useState(1440);
  const [retries, setRetries] = useState(2);
  const [review, setReview] = useState<Approval | null>(null);
  const [investigation, setInvestigation] = useState<Approval | null>(null);
  const [chargeRun, setChargeRun] = useState<Run | null>(null);
  const [chargeOutcome, setChargeOutcome] = useState("");
  const [chargeNotes, setChargeNotes] = useState("");
  const [eventWork, setEventWork] = useState<Work | null>(null);
  const [eventToken, setEventToken] = useState<{token: string; path: string} | null>(null);
  const [outcome, setOutcome] = useState("");
  const [evidence, setEvidence] = useState("");
  const [confirmed, setConfirmed] = useState(false);
  const openInvestigation = (a: Approval) => { setError(""); setInvestigation(a); setOutcome(""); setEvidence(""); setConfirmed(false); };
  const [editArgs, setEditArgs] = useState<Record<string,string> | null>(null);
  const [detail, setDetail] = useState<Run | null>(null);
  const [answer, setAnswer] = useState("");
  const [schedule, setSchedule] = useState<Work | null>(null);
  const [cron, setCron] = useState("0 9 * * 1-5");
  const [zone, setZone] = useState(() => Intl.DateTimeFormat().resolvedOptions().timeZone);
  const [notesAgent, setNotesAgent] = useState("");
  const [notes, setNotes] = useState<Note[]>([]);
  const [note, setNote] = useState<Note>({ note_id: "", title: "", content: "" });

  const load = useCallback(async () => {
    const [overview, list, knowledge] = await Promise.all([api<Overview>("overview"), fetchAgentIdentities(), api<{sources: Source[]}>("knowledge")]);
    setSources(knowledge.sources);
    setData(overview); setAgents(list.agents); setError("");
  }, []);
  useEffect(() => { void load().catch(e => setError(e.message)); }, [load]);
  useEffect(() => { const wanted = new URLSearchParams(window.location.search).get("tab"); if (wanted && ["work", "needs", "history"].includes(wanted)) setTab(wanted); }, []);
  useEffect(() => { const timer = setInterval(() => { if (!busy && !review && !investigation && !creating && !notesAgent && !schedule && !chargeRun && !eventWork) void load().catch(e => setError(e.message)); }, 10000); return () => clearInterval(timer); }, [busy, review, investigation, creating, notesAgent, schedule, chargeRun, eventWork, load]);
  useEffect(() => {
    if (!data || tab !== "work") return;
    const target = window.location.hash.slice(1);
    if (target.startsWith("work-")) document.getElementById(target)?.scrollIntoView({block: "center"});
  }, [data, tab]);
  useEffect(() => {
    setDetail(current => current ? data?.runs.find(run => run.run_id === current.run_id) || current : null);
  }, [data]);
  const act = async (fn: () => Promise<unknown>, message = "Saved") => {
    if (busy) return;
    setBusy(true); setError(""); setNotice("");
    try { await fn(); await load(); setNotice(message); }
    catch (e) { setError(e instanceof Error ? e.message : "Request failed"); }
    finally { setBusy(false); }
  };
  const pending = data?.approvals.filter(a => a.status === "pending" && new Date(a.expires_at) > new Date()) || [];
  const unresolved = data?.approvals.filter(a => a.status === "uncertain" && writeActions.includes(a.action) && a.provider_check?.outcome !== "sent" && !["sent", "not_sent"].includes(a.reconciliation?.outcome || "")) || [];
  const charges = data?.runs.filter(chargeUnresolved) || [];
  const questions = data?.runs.filter(r => r.status === "needs_input") || [];
  const jobName = (id: string) => data?.work.find(w => w.work_id === id)?.title || "Delegated work";
  const decide = (decision: string) => act(async () => {
    if (!review) return;
    await api(`approvals/${review.approval_id}`, { decision, version: review.version, ...(decision === "edit" ? { args: editArgs } : {}) });
    setReview(null); setEditArgs(null);
  }, decision === "approve" ? "Approved. Execution is checked separately; watch for a delivery receipt." : decision === "edit" ? "New version saved. Review it again before approving." : "Decision saved");
  const openNotes = async (id: string) => { setNotesAgent(id); setNotes([]); setNote({ note_id: "", title: "", content: "" }); try { setNotes((await api<{notes: Note[]}>(`notes/${id}`)).notes); } catch(e) { setError((e as Error).message); } };

  return <main className="mx-auto h-full w-full max-w-6xl space-y-6 overflow-y-auto p-4 pb-28 md:p-8 md:pb-12">
    <header className="flex flex-wrap items-start justify-between gap-4">
      <div><Link className="text-sm text-muted-foreground underline" href={`${basePath}/agents`}>Agents</Link><h1 className="mt-2 text-2xl font-semibold">Agent work</h1><p className="mt-1 text-sm text-muted-foreground">Give a job. Review what needs you. See what got done.</p></div>
      <div className="flex gap-2"><Button variant="outline" disabled={!data} onClick={() => setLibrary(true)}>Playbook library</Button><Button onClick={() => setCreating(true)} disabled={!data}>New work</Button></div>
    </header>
    {error && <div role="alert" className="rounded-xl border border-destructive p-3 text-sm">{error}<Button variant="ghost" size="sm" onClick={() => void load().catch(e => setError(e.message))}>Retry</Button></div>}
    {notice && <div role="status" className="flex items-center justify-between gap-3 rounded-xl bg-muted p-3 text-sm">{notice}<Button variant="ghost" size="sm" onClick={() => setNotice("")}>Dismiss</Button></div>}
    {data && (!data.model_ready || !data.pricing_ready || !data.worker_enabled) && <p role="status" className="rounded-xl border border-amber-300 p-3 text-sm">{!data.model_ready ? "Setup needed: ask an admin to connect the bounded-work model. You can save work, but it cannot run yet." : !data.pricing_ready ? "Setup needed: ask an admin to configure model price ceilings. Provider calls are blocked until pricing is configured." : "Worker is off. Runs stay queued until the scheduler is enabled."}</p>}
    <nav aria-label="Work views" className="flex flex-wrap gap-2 border-b pb-3">{[["work", "Work"], ["needs", `Needs you (${pending.length + questions.length + unresolved.length + charges.length})`], ["history", "Run history"]].map(([id, label]) => <Button key={id} variant={tab === id ? "default" : "ghost"} aria-pressed={tab === id} onClick={() => setTab(id)}>{label}</Button>)}</nav>
    {data?.attention_limited && <p role="status" className="rounded-lg border border-amber-300 p-3 text-sm">Large backlog: this view prioritizes the oldest 200 items of each attention type. More may remain; resolve these and refresh. The taskboard shows the total count.</p>}
    {!data && !error && <p role="status">Loading work…</p>}
    {tab === "work" && data && <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{data.work.length === 0 && <section className="col-span-full rounded-xl border border-dashed p-10 text-center"><h2 className="font-medium">Your agents have no work yet</h2><p className="mt-2 text-sm text-muted-foreground">Start with one small job and test it without accessing connected accounts.</p><Button className="mt-4" onClick={() => setCreating(true)}>Create your first job</Button></section>}{data.work.map(w => {
      const runs = data.runs.filter(r => r.work_id === w.work_id);
      const unknown = unresolved.filter(a => a.work_id === w.work_id).length;
      const count = pending.filter(a => a.work_id === w.work_id).length;
      return <section key={w.work_id} id={`work-${w.work_id}`} tabIndex={-1} aria-label={w.title} className="min-w-0 space-y-3 rounded-xl border p-4">
        <div className="flex justify-between gap-2 text-xs"><span className="font-semibold uppercase tracking-wide">⚙ Work</span><span>{w.revoked ? "Revoked" : w.paused ? "Paused" : "Enabled"}</span></div>
        <h2 className="break-words font-semibold">{w.title}</h2><p className="break-words text-sm text-muted-foreground">{w.success}</p>
        <p className="break-all text-xs">Account: {w.owner}</p><p className="text-xs">{w.knowledge_ids?.length || 0} attached playbooks · Personal notes stay private</p><p className="text-xs">{w.cron ? `Schedule: ${w.cron} · ${w.timezone}` : "Manual or event-triggered"}</p>
        <p className="text-xs">Next wake-up: {w.paused ? "Paused" : w.next_run_at ? new Date(w.next_run_at).toLocaleString() : w.cron ? "Waiting for scheduler" : "When you start a run"}</p>{w.schedule_error && <p className="text-xs text-destructive">Schedule needs attention: {w.schedule_error}</p>}
        <p className="text-xs text-muted-foreground">{w.max_steps} model calls shared with delegates. Saved agent instructions.</p><p className="text-xs text-muted-foreground">Each run: {usd((w.max_cost_microusd ?? 1000000) * 1000)} model budget · {w.max_runtime_minutes || 1440} minute deadline · {w.max_planner_retries ?? 2} model {(w.max_planner_retries ?? 2) === 1 ? "retry" : "retries"}</p><details className="text-xs"><summary className="cursor-pointer underline">Review saved job and permissions</summary><p className="mt-2 whitespace-pre-wrap break-words">{w.instructions}</p>{Object.entries(w.policy.actions).map(([action,mode]) => <p key={action}>{actions[action as keyof typeof actions]}: {mode === "ask" ? "Ask me each time" : mode === "allow" ? "Allowed automatically" : "Never"}</p>)}<p className="mt-2 break-all">Recipients: {w.policy.recipients.join(", ") || "None (email sending blocked)"}</p><p className="break-all">Slack channels: {(w.policy.channels || []).join(", ") || "None (Slack sending blocked)"}</p><p className="mt-2">To change the grant, create a new job. Existing runs keep the saved version.</p></details>
        {count > 0 && <Button variant="outline" className="border-amber-400" onClick={() => setTab("needs")}>{count} approvals need you</Button>}
        {unknown > 0 && <Button variant="outline" className="border-amber-400" onClick={() => setTab("needs")}>{unknown} delivery outcomes need review</Button>}
        {runs[0] && <button className="block text-left text-sm underline" onClick={() => {setDetail(runs[0]); setAnswer("");}}>Latest: {statusLabel(runs[0].status)}{runs[0].dry_run ? " (safe test)" : ""}</button>}
        {!w.revoked && <div className="flex flex-wrap gap-2">
          <Button size="sm" variant="outline" disabled={busy || !data.model_ready} onClick={() => void act(() => api(`work/${w.work_id}/test`, { event_key: crypto.randomUUID() }), "Safe test queued. No connected-account reads or writes will execute.")}>Safe test</Button>
          <Button size="sm" disabled={busy || !data.model_ready} onClick={() => void act(() => api(`work/${w.work_id}/${w.paused ? "enable" : "pause"}`, {}), w.paused ? "Work enabled. Run it now or add a schedule." : "Future triggers paused. Running work is not stopped.")}>{w.paused ? "Enable work" : "Pause triggers"}</Button>
          {!w.paused && <Button size="sm" variant="outline" disabled={busy} onClick={() => void act(() => api(`work/${w.work_id}/run`, { event_key: crypto.randomUUID() }), "Run queued")}>Run now</Button>}
          <Button size="sm" variant="ghost" onClick={() => {setCron(w.cron || "0 9 * * 1-5"); setZone(w.timezone || Intl.DateTimeFormat().resolvedOptions().timeZone); setSchedule(w);}}>{w.flow_id ? "Edit schedule" : "Add schedule"}</Button>
          <Button size="sm" variant="ghost" disabled={busy} onClick={() => void openNotes(w.agent_id)}>Private notes</Button>
          <Button size="sm" variant="ghost" onClick={() => { setError(""); setEventWork(w); setEventToken(null); }}>Event trigger</Button>
        </div>}
      </section>;
    })}</div>}
    {tab === "needs" && <div className="space-y-4">{pending.length + questions.length + unresolved.length + charges.length === 0 && <p className="py-12 text-center text-muted-foreground">Nothing needs your attention.</p>}{charges.map(r => <section key={r.run_id} className="min-w-0 space-y-2 rounded-xl border border-amber-400 p-4"><p className="text-xs font-semibold uppercase">⚠ Model charge review · Not an approval</p><h2 className="break-words font-medium">A model call in {jobName(r.work_id)} has an unknown billing outcome</h2><p className="text-xs text-muted-foreground">Funds stay reserved. Recording what you verified never releases budget, restarts work or changes what was billed.</p><Button variant="outline" onClick={() => { setError(""); setChargeRun(r); setChargeOutcome(""); setChargeNotes(""); }}>Review reserved charge</Button></section>)}{unresolved.map(a => <section key={a.approval_id} className="min-w-0 space-y-2 rounded-xl border border-amber-400 p-4"><p className="text-xs font-semibold uppercase">⚠ Delivery review · Not an approval</p><h2 className="break-words font-medium">{a.action === "slack.send" ? `Did the Slack message to ${a.args.channel} send?` : `Did the email to ${a.args.to} send?`}</h2><p className="break-words text-sm">{a.args.subject || a.args.text}</p><p className="break-all text-xs">Account: {a.owner}</p><p className="text-xs text-muted-foreground">{jobName(a.work_id)}. No reliable receipt was saved. Do not resend.</p><Button variant="outline" onClick={() => openInvestigation(a)}>Investigate delivery</Button></section>)}{questions.map(r => <section key={r.run_id} className="rounded-xl border p-4"><p className="text-xs font-semibold uppercase">Question · Not an approval</p><h2 className="mt-2 font-medium">{r.question}</h2><p className="text-sm text-muted-foreground">{jobName(r.work_id)}</p><Button className="mt-3" onClick={() => {setDetail(r); setAnswer("");}}>Answer question</Button></section>)}{pending.map(a => <section key={a.approval_id} className="min-w-0 space-y-2 rounded-xl border border-amber-400 bg-amber-50/40 p-4 dark:bg-amber-950/10"><p className="text-xs font-semibold uppercase tracking-wide">✋ Approval · Needs you</p><h2 className="break-words font-medium">{a.action === "gmail.send" ? `Send email to ${a.args.to}` : a.action === "slack.send" ? `Send Slack message to ${a.args.channel}` : `Authorize ${a.action}`}</h2><p className="text-sm">{a.args.subject || a.reason}</p><p className="text-xs text-muted-foreground">From work: {jobName(a.work_id)} · Expires {new Date(a.expires_at).toLocaleString()}</p><Button variant="outline" onClick={() => {setReview(a); setEditArgs(null);}}>Review exact action</Button></section>)}</div>}
    {tab === "history" && <div className="space-y-3">{data?.approvals.filter(a => ["executed", "uncertain", "executing", "rejected", "expired"].includes(a.status)).map(a => <details key={a.approval_id} className="rounded-xl border p-3 text-sm"><summary className="cursor-pointer">✋ {a.action} · {a.provider_check?.outcome === "sent" ? "Verified in Gmail Sent" : statusLabel(a.status)}</summary><p className="mt-2 break-all">Account: {a.owner}</p>{a.provider_check?.outcome === "sent" ? <details className="mt-2"><summary className="cursor-pointer text-xs underline">Original execution receipt (before verification)</summary><pre className="mt-2 whitespace-pre-wrap break-words text-xs">{JSON.stringify(a.receipt || {status:a.status},null,2)}</pre></details> : <pre className="mt-2 whitespace-pre-wrap break-words text-xs">{JSON.stringify(a.receipt || {status:a.status},null,2)}</pre>}{a.provider_check && <ProviderCheck approval={a} />}{a.status === "uncertain" && a.provider_check?.outcome !== "sent" && <p className="mt-2 text-destructive">{a.reconciliation ? `Owner report: ${{sent:"sent",not_sent:"not sent",unknown:"still unknown"}[a.reconciliation.outcome]}. This is not a provider receipt. Repeat execution remains blocked.` : writeActions.includes(a.action) ? "Do not resend. Verify with the provider before recording an outcome." : "No reliable result was saved. Check your connections before starting new work."}</p>}{a.status === "uncertain" && writeActions.includes(a.action) && <Button className="mt-2" variant="outline" onClick={() => openInvestigation(a)}>{a.reconciliation ? "Review investigation" : "Investigate delivery"}</Button>}{a.reconciliation && <p className="mt-2 whitespace-pre-wrap break-words">Owner investigation notes: {a.reconciliation.evidence}</p>}</details>)}{!data?.runs.length && <p className="py-12 text-center text-muted-foreground">Completed work and safe tests appear here.</p>}{data?.runs.map(r => <button key={r.run_id} onClick={() => {setDetail(r); setAnswer("");}} className="flex w-full flex-wrap items-center justify-between gap-2 rounded-xl border p-4 text-left hover:bg-muted"><span className="break-words font-medium">{jobName(r.work_id)}{r.dry_run && " · Safe test"}{r.parent_id && " · Delegate"}</span><span className="text-sm">{statusLabel(r.status)} · {r.step}/{r.max_steps} steps</span></button>)}</div>}
    <KnowledgeLibrary open={library} onOpenChange={setLibrary} owner={user?.email || ""} onSaved={load} />
    <Dialog open={creating} onOpenChange={v => { if (!busy) setCreating(v); }}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Give an agent a job</DialogTitle><DialogDescription>Start small. Permissions are enforced by a bounded runner, not prompt instructions.</DialogDescription></DialogHeader>
      {error && <p role="alert" className="text-sm text-destructive">{error}</p>}
      <form className="space-y-4" onSubmit={e => {e.preventDefault(); void act(async () => { await api("work", { knowledge_ids: knowledgeIds, title, agent_id: agentId, instructions, success, policy: { ...policy, recipients: recipients.split(/[\n,]/).map(s => s.trim()).filter(Boolean), channels: channels.split(/[\n,]/).map(s => s.trim()).filter(Boolean) }, delegates, max_steps: budget, max_runtime_minutes: runtime, max_planner_retries: retries, max_cost_microusd: Math.round(Number(costBudget) * 1000000) }); setCreating(false); setKnowledgeIds([]); setTitle(""); setInstructions(""); setSuccess(""); }, "Work saved paused. Run a safe test, then enable it when ready.");}}>
        <div><Label htmlFor="template">Start from a template</Label><select id="template" className={select} defaultValue="" onChange={e => {if (e.target.value) {setTitle(e.target.value); setSuccess("A concise summary and proposed next actions for my review."); setInstructions(e.target.value === "Invoice follow-up" ? "Review the invoice information in my notes and recent Gmail messages. Draft a polite reminder only for explicitly allowed recipients. Ask for missing invoice details." : "Review my attached notes and report the key facts, open questions and recommended next steps. Ask for missing source information.");}}}><option value="">Custom job</option><option>Invoice follow-up</option><option>Meeting preparation</option><option>Support triage</option></select></div>
        <div><Label htmlFor="agent">Who should do it?</Label><select id="agent" className={select} required value={agentId} onChange={e => setAgentId(e.target.value)}><option value="">Select agent</option>{agents.map(a => <option key={a.agent_id} value={a.agent_id}>{a.name}</option>)}</select></div>
        <div><Label htmlFor="job-title">Job</Label><Input id="job-title" required maxLength={120} value={title} onChange={e => setTitle(e.target.value)} /></div>
        <fieldset className="space-y-2 rounded-lg border p-3"><legend className="px-1 text-sm font-medium">Attach playbooks</legend><p className="text-xs text-muted-foreground">Only selected playbooks are read. They stay separate from personal notes. Access is rechecked before each step; removal of access blocks dependent work.</p>{sources.length === 0 && <p className="text-sm">No playbooks yet. Save one in the Playbook library before creating this job.</p>}{sources.map(source => <label key={source.source_id} className="flex items-start gap-2 text-sm"><input type="checkbox" checked={knowledgeIds.includes(source.source_id)} disabled={!knowledgeIds.includes(source.source_id) && knowledgeIds.length >= 10} onChange={e => setKnowledgeIds(e.target.checked ? [...knowledgeIds, source.source_id] : knowledgeIds.filter(id => id !== source.source_id))} /><span className="break-words">{source.title}<span className="block break-all text-xs text-muted-foreground">{source.owner === user?.email ? "Yours" : `Shared by ${source.owner}`}</span></span></label>)}</fieldset>
        <div><Label htmlFor="instructions">Instructions and sources</Label><Textarea id="instructions" required maxLength={8000} value={instructions} onChange={e => setInstructions(e.target.value)} /></div>
        <div><Label htmlFor="success">What should a good result look like?</Label><Textarea id="success" required maxLength={2000} value={success} onChange={e => setSuccess(e.target.value)} /></div>
        <p className="text-xs">Google: {data?.google_connected ? "Connected (permissions rechecked on execution)" : "Not connected. Connect Google in Integrations before live Gmail or Calendar work."} · Slack: {data?.slack_connected ? "Connected" : "Not connected; Slack sends will fail until connected."}</p><fieldset className="space-y-3 rounded-xl border p-3"><legend className="px-1 text-sm font-semibold">Permissions</legend><p className="text-xs text-muted-foreground">Unknown actions, shell commands, arbitrary URLs and other accounts are blocked. Gmail reads cover your mailbox. Allowing both reads also enables up to five automatic Sent-folder checks after an uncertain send, even after the run ends. Revoking work stops future checks.</p>{Object.entries(actions).map(([key,label]) => <div key={key} className="grid grid-cols-2 items-center gap-3"><Label htmlFor={key}>{label}</Label><select id={key} className={select} value={policy.actions[key]} onChange={e => setPolicy({...policy, actions: {...policy.actions, [key]: e.target.value as Mode}})}><option value="deny">Never</option><option value="ask">Ask me each time</option><option value="allow">Allow automatically</option></select></div>)}<Label htmlFor="recipients">Allowed email recipients (exact addresses)</Label><Textarea id="recipients" value={recipients} onChange={e => setRecipients(e.target.value)} placeholder="One address per line. Empty means no sending." /><Label htmlFor="channels">Allowed Slack channel IDs (exact IDs like C0123ABCD)</Label><Textarea id="channels" value={channels} onChange={e => setChannels(e.target.value)} placeholder="One channel ID per line. Empty means no Slack sending." /><p className="break-all text-xs">Uses {user?.email}. Nothing inherits the agent creator’s credentials.</p></fieldset>
        <fieldset className="space-y-2"><legend className="text-sm font-medium">Allowed delegates (optional)</legend><p className="text-xs text-muted-foreground">One level only. Same account and shared budget. No extra permissions.</p>{agents.filter(a => a.agent_id !== agentId).map(a => <label key={a.agent_id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={delegates.includes(a.agent_id)} onChange={e => setDelegates(e.target.checked ? [...delegates,a.agent_id] : delegates.filter(id => id !== a.agent_id))} />{a.name}</label>)}</fieldset>
        <div><Label htmlFor="budget">Maximum model calls (including delegates)</Label><Input id="budget" type="number" min={1} max={30} required value={budget} onChange={e => setBudget(Number(e.target.value))} /><p className="mt-1 text-xs text-muted-foreground">Up to 2,048 output tokens per call. Retries and delegates share both limits.</p></div>
        <div><Label htmlFor="cost-budget">Model budget per run (USD)</Label><Input id="cost-budget" type="number" min="0.01" max="100" step="0.01" required value={costBudget} onChange={e => setCostBudget(e.target.value)} /><p className="mt-1 text-xs text-muted-foreground">Includes safe tests, retries and delegates within each run. A new scheduled run gets a fresh budget. Calls reserve their full possible cost first, so a small budget may stop work early. Connector charges excluded.</p></div>
        <fieldset className="space-y-3 rounded-xl border p-3"><legend className="px-1 text-sm font-medium">When should it stop?</legend>
          <div><Label htmlFor="runtime">Finish within (minutes)</Label><Input id="runtime" type="number" min={1} max={43200} required value={runtime} onChange={e => setRuntime(Number(e.target.value))} /><p className="mt-1 text-xs text-muted-foreground">Default: 24 hours. Starts when a run is queued, including time waiting for you and delegates. Expired approvals cannot execute.</p></div>
          <div><Label htmlFor="retries">Retries for temporary model failures</Label><select id="retries" className={select} value={retries} onChange={e => setRetries(Number(e.target.value))}><option value={0}>No retries</option><option value={1}>1 retry</option><option value={2}>2 retries (recommended)</option><option value={3}>3 retries</option></select><p className="mt-1 text-xs text-muted-foreground">Retries count toward the model-call limit and wait 30, 60, then 120 seconds. Email delivery with an unknown outcome is never retried.</p></div>
        </fieldset>
        <div className="flex justify-end gap-2"><Button type="button" variant="outline" disabled={busy} onClick={() => setCreating(false)}>Cancel</Button><Button disabled={busy}>{busy ? "Saving…" : "Save paused work"}</Button></div>
      </form>
    </DialogContent></Dialog>
    <Dialog open={!!review} onOpenChange={v => {if (!v && !busy) {setReview(null); setEditArgs(null);}}}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Review before authorizing</DialogTitle><DialogDescription>Approval applies only to this version. It does not mean the action has executed.</DialogDescription></DialogHeader>{review && <div className="space-y-4">
      {error && <p role="alert" className="text-sm text-destructive">{error}</p>}
      <p className="text-sm">{review.reason}</p><dl className="space-y-2 text-sm"><div><dt className="font-medium">Account</dt><dd className="break-all">{review.owner}</dd></div><div><dt className="font-medium">Action</dt><dd>{review.action} · Version {review.version}</dd></div></dl>
      {Object.entries(editArgs || review.args).map(([key,value]) => <div key={key}><Label htmlFor={`review-${key}`}>{{to:"Recipient",subject:"Subject",body:"Message",query:"Search query",message_id:"Message ID",channel:"Slack channel ID",text:"Message"}[key] || key}</Label>{editArgs ? <Textarea id={`review-${key}`} value={value} onChange={e => setEditArgs({...editArgs,[key]:e.target.value})} rows={key === "body" ? 8 : 2} /> : <p id={`review-${key}`} className="mt-1 whitespace-pre-wrap break-words rounded-lg bg-muted p-3 text-sm">{value}</p>}</div>)}
      <p className="text-xs text-muted-foreground">Expires {new Date(review.expires_at).toLocaleString()}. Editing creates a new version that must be reviewed again.</p>
      <div className="flex flex-wrap gap-2">{editArgs ? <><Button disabled={busy} onClick={() => void decide("edit")}>Save new version</Button><Button variant="outline" disabled={busy} onClick={() => setEditArgs(null)}>Cancel edit</Button></> : <><Button disabled={busy} onClick={() => void decide("approve")}>{writeActions.includes(review.action) ? "Approve & send" : "Approve this action"}</Button><Button variant="outline" disabled={busy} onClick={() => setEditArgs({...review.args})}>Edit proposal</Button><Button variant="ghost" disabled={busy} onClick={() => void decide("reject")}>Reject</Button></>}</div>
    </div>}</DialogContent></Dialog>
    <Dialog open={!!investigation} onOpenChange={v => {if (!v && !busy) setInvestigation(null);}}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{investigation?.action === "slack.send" ? "Investigate Slack delivery" : "Investigate email delivery"}</DialogTitle><DialogDescription>Record what you verified with the provider. This does not send anything, authorize a retry or resume the run.</DialogDescription></DialogHeader>{investigation && <form className="space-y-4" onSubmit={e => {e.preventDefault(); void act(async () => {await api(`approvals/${investigation.approval_id}/reconcile`, {version: investigation.reconciliation?.version || 0, outcome, evidence}); setInvestigation(null);}, "Investigation recorded. Nothing was re-sent and no run resumed. Repeat execution remains blocked.");}}>
      {error && <p role="alert" className="text-sm text-destructive">{error}</p>}
      {investigation.provider_check ? <ProviderCheck approval={investigation} /> : <p className="text-sm text-muted-foreground">{investigation.action === "slack.send" ? "Slack sends have no automatic provider check. Open the channel in Slack and look for the exact message." : investigation.provider_message_id ? "Automatic checks require saved Gmail search and read permissions. They never resend." : "This older action has no tracking ID. Check Gmail manually."}</p>}
      <dl className="space-y-2 text-sm"><div><dt className="font-medium">Account to check</dt><dd className="break-all">{investigation.owner}</dd></div><div><dt className="font-medium">{investigation.action === "slack.send" ? "Channel ID" : "Recipient"}</dt><dd className="break-all">{investigation.args.to || investigation.args.channel}</dd></div>{investigation.args.subject && <div><dt className="font-medium">Subject</dt><dd className="break-words">{investigation.args.subject}</dd></div>}</dl>
      <details><summary className="cursor-pointer text-sm underline">Review exact message and original receipt</summary><p className="mt-2 whitespace-pre-wrap break-words text-sm">{investigation.args.body || investigation.args.text}</p><pre className="mt-2 whitespace-pre-wrap break-words text-xs">{JSON.stringify(investigation.receipt || {},null,2)}</pre><p className="mt-2 break-all text-xs">Action ID: {investigation.approval_id}</p></details>
      <p className="text-sm">{investigation.action === "slack.send" ? "Open the channel above in Slack as this account and look for the exact message near the attempt time. A missing message alone is not proof it was not sent (it may have been deleted). Choose “Still unknown” if unsure." : "Check Sent mail in the account above and match the recipient, subject and message. A missing search result alone is not proof that it was not sent. Choose “Still unknown” if unsure."}</p>
      {investigation.reconciliation_history?.length ? <details><summary className="cursor-pointer text-sm underline">Previous investigation notes ({investigation.reconciliation_history.length})</summary>{investigation.reconciliation_history.map(r => <div key={r.version} className="mt-2 rounded-lg bg-muted p-3 text-xs"><p className="break-all">{r.actor} · {new Date(r.at).toLocaleString()} · Owner reported: {r.outcome.replaceAll("_"," ")}</p><p className="whitespace-pre-wrap break-words">{r.evidence}</p></div>)}</details> : null}
      <div><Label htmlFor="delivery-outcome">What did you verify?</Label><select id="delivery-outcome" className={select} required value={outcome} onChange={e => {setOutcome(e.target.value); setConfirmed(false);}}><option value="">Select an outcome</option><option value="sent">Sent: matching message confirmed</option><option value="not_sent">Not sent: confirmed with provider evidence</option><option value="unknown">Still unknown: keep in Needs you</option></select></div>
      <div><Label htmlFor="delivery-evidence">Evidence or investigation notes</Label><Textarea id="delivery-evidence" required maxLength={2000} rows={4} value={evidence} onChange={e => setEvidence(e.target.value)} placeholder="Message ID, time checked and matching details, or what you still need to verify. Do not paste passwords or tokens." /></div>
      <label className="flex items-start gap-2 text-sm"><input type="checkbox" className="mt-1" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} />I understand this records my report, not an automated provider verification. It will not resend anything.</label>
      <div className="flex flex-wrap gap-2"><Button disabled={busy || !outcome || !evidence.trim() || !confirmed}>{busy ? "Saving…" : "Record investigation"}</Button><Button type="button" variant="outline" disabled={busy} onClick={() => setInvestigation(null)}>Cancel</Button></div>
    </form>}</DialogContent></Dialog>
    <Dialog open={!!detail} onOpenChange={v => {if (!v) setDetail(null);}}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{detail ? jobName(detail.work_id) : "Run"}</DialogTitle><DialogDescription>Progress and receipts. Chat or board movement cannot authorize actions.</DialogDescription></DialogHeader>{detail && <div className="space-y-4"><p>{statusLabel(detail.status)}{detail.dry_run && " · No external actions"}</p>{detail.result && <p className="whitespace-pre-wrap break-words text-sm">{detail.result}</p>}{detail.event_note && <details className="rounded-lg border p-3 text-sm"><summary className="cursor-pointer">External event note (untrusted data, not instructions)</summary><p className="mt-2 whitespace-pre-wrap break-words">{detail.event_note}</p></details>}{detail.status === "needs_input" && <form onSubmit={e => {e.preventDefault(); void act(async () => {await api(`runs/${detail.run_id}/answer`, {answer}); setDetail(null);}, "Answer saved. No extra permissions granted.");}} className="space-y-3"><Label htmlFor="answer">{detail.question}</Label><Textarea id="answer" value={answer} required onChange={e => setAnswer(e.target.value)} /><Button disabled={busy}>Answer &amp; resume</Button></form>}<p className="text-xs">Deadline: {detail.deadline_at ? new Date(detail.deadline_at).toLocaleString() : "24 hours from creation"}. Includes approval waits and delegates.</p><CostSummary run={detail} />{chargeUnresolved(detail) && <Button variant="outline" disabled={busy} onClick={() => { setError(""); setChargeRun(detail); setChargeOutcome(""); setChargeNotes(""); }}>Review reserved model charge</Button>}{detail.cost_review && <p className="text-xs">Charge review: owner reported {detail.cost_review.outcome.replaceAll("_", " ")} · {new Date(detail.cost_review.at).toLocaleString()}. Reserved funds are never released by a report.</p>}<p className="text-xs">Model calls used: {detail.calls_used}/{detail.max_steps} · Model retries: {detail.planner_retries || 0}</p>{["done","failed","cancelled"].includes(detail.status) ? <p className="text-xs">This run has ended. No further wake-ups.</p> : detail.status === "queued" ? <p className="text-xs">Next eligible wake: {new Date(detail.wake_at).toLocaleString()}</p> : <p className="text-xs">{detail.status === "running" ? "A step is in progress." : "Resumes when the required input, approval or delegate result arrives."}</p>}{detail.history.map((h,i) => <pre key={i} className="whitespace-pre-wrap break-words rounded-lg bg-muted p-3 text-xs">{JSON.stringify(h,null,2)}</pre>)}{!["done","failed","cancelled"].includes(detail.status) && <Button variant="outline" disabled={busy} onClick={() => void act(async () => {await api(`runs/${detail.run_id}/cancel`, {}); setDetail(null);}, "Stop requested. An external action already in progress may still complete.")}>Stop this run and delegates</Button>}</div>}</DialogContent></Dialog>
    <Dialog open={!!schedule} onOpenChange={v => {if (!v && !busy) setSchedule(null);}}><DialogContent><DialogHeader><DialogTitle>{schedule?.flow_id ? "Edit schedule" : "Add a schedule"}</DialogTitle><DialogDescription>Uses Flows. Saved paused; enable work after reviewing it.</DialogDescription></DialogHeader>{error && <p role="alert" className="text-destructive">{error}</p>}<form className="space-y-4" onSubmit={e => {e.preventDefault(); void act(async () => {await api(`work/${schedule!.work_id}/schedule`, {cron, timezone:zone}); setSchedule(null);}, "Schedule saved paused. Enable the job to start future wake-ups.");}}><Label htmlFor="schedule-preset">Repeat</Label><select id="schedule-preset" className={select} value={["0 9 * * 1-5","0 9 * * *","0 * * * *"].includes(cron) ? cron : "custom"} onChange={e => setCron(e.target.value === "custom" ? "30 9 * * 1-5" : e.target.value)}><option value="0 9 * * 1-5">Weekdays at 9:00 AM</option><option value="0 9 * * *">Every day at 9:00 AM</option><option value="0 * * * *">Every hour</option><option value="custom">Custom schedule</option></select><Label htmlFor="cron">Cron expression (advanced)</Label><Input id="cron" value={cron} onChange={e => setCron(e.target.value)} required /><p className="text-xs">Default: Monday to Friday at 9:00. Missed executions coalesce; no replay storm.</p><Label htmlFor="timezone">Timezone</Label><Input id="timezone" value={zone} onChange={e => setZone(e.target.value)} required /><Button disabled={busy}>Save paused schedule</Button></form></DialogContent></Dialog>
    <Dialog open={!!chargeRun} onOpenChange={v => {if (!v && !busy) setChargeRun(null);}}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Review a reserved model charge</DialogTitle><DialogDescription>A model call ended without a trustworthy billing result, so its full reserved cost stays committed. Record what you verified on your provider invoice. This never releases funds, changes budgets or restarts work.</DialogDescription></DialogHeader>{chargeRun && <form className="space-y-4" onSubmit={e => {e.preventDefault(); void act(async () => {await api(`runs/${chargeRun.run_id}/cost-review`, {version: chargeRun.cost_review?.version || 0, outcome: chargeOutcome, notes: chargeNotes}); setChargeRun(null);}, "Charge review recorded. Reserved funds stay reserved; nothing was re-run.");}}>
      {error && <p role="alert" className="text-sm text-destructive">{error}</p>}
      <CostSummary run={chargeRun} />
      <dl className="space-y-2 text-sm"><div><dt className="font-medium">Job</dt><dd className="break-words">{jobName(chargeRun.work_id)}</dd></div><div><dt className="font-medium">Unresolved reservations</dt><dd>{(chargeRun.cost_ledger || []).filter(en => en.status === "held").length} model {(chargeRun.cost_ledger || []).filter(en => en.status === "held").length === 1 ? "call" : "calls"} without a recorded billing result</dd></div></dl>
      {chargeRun.cost_review_history?.length ? <details><summary className="cursor-pointer text-sm underline">Previous charge reviews ({chargeRun.cost_review_history.length})</summary>{chargeRun.cost_review_history.map(r => <div key={r.version} className="mt-2 rounded-lg bg-muted p-3 text-xs"><p className="break-all">{r.actor} · {new Date(r.at).toLocaleString()} · Reported: {r.outcome.replaceAll("_", " ")}</p><p className="whitespace-pre-wrap break-words">{r.notes}</p></div>)}</details> : null}
      <div><Label htmlFor="charge-outcome">What did your provider invoice show?</Label><select id="charge-outcome" className={select} required value={chargeOutcome} onChange={e => setChargeOutcome(e.target.value)}><option value="">Select an outcome</option><option value="billed">Billed: the call appears on the invoice</option><option value="not_billed">Not billed: confirmed absent from the invoice</option><option value="unknown">Still unknown: keep in Needs you</option></select></div>
      <div><Label htmlFor="charge-notes">Invoice evidence or notes</Label><Textarea id="charge-notes" required maxLength={2000} rows={3} value={chargeNotes} onChange={e => setChargeNotes(e.target.value)} placeholder="Invoice line, date range checked, or what you still need to verify. Do not paste API keys." /></div>
      <div className="flex flex-wrap gap-2"><Button disabled={busy || !chargeOutcome || !chargeNotes.trim()}>{busy ? "Saving…" : "Record charge review"}</Button><Button type="button" variant="outline" disabled={busy} onClick={() => setChargeRun(null)}>Cancel</Button></div>
    </form>}</DialogContent></Dialog>
    <Dialog open={!!eventWork} onOpenChange={v => {if (!v && !busy) {setEventWork(null); setEventToken(null);}}}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Wake this job from an external event</DialogTitle><DialogDescription>Systems can queue one deduplicated run of this exact job by calling a webhook with a secret token. Events cannot change instructions, permissions or budgets, and event notes are treated as untrusted data.</DialogDescription></DialogHeader>{eventWork && <div className="space-y-4">
      {error && <p role="alert" className="text-sm text-destructive">{error}</p>}
      <p className="text-sm">Job: <span className="font-medium">{eventWork.title}</span> · runs as <span className="break-all">{eventWork.owner}</span> under its saved permissions.</p>
      <p className="text-sm text-muted-foreground">Events only start runs while the job is enabled. Repeated calls with the same <code>event_key</code> are ignored, and a job runs one event at a time.</p>
      {eventToken ? <div className="space-y-2 rounded-lg border p-3"><p className="text-sm font-medium">Copy this token now. It is shown once and stored only as a hash.</p><pre className="overflow-x-auto whitespace-pre-wrap break-all rounded bg-muted p-2 text-xs">{eventToken.token}</pre><p className="text-sm font-medium">Send events with:</p><pre className="overflow-x-auto whitespace-pre-wrap break-all rounded bg-muted p-2 text-xs">{`curl -X POST "$LOMA_URL${eventToken.path}" \\\n  -H "X-Work-Event-Token: <token>" \\\n  -H "Content-Type: application/json" \\\n  -d '{"event_key": "unique-id", "note": "optional context (untrusted)"}'`}</pre></div> : <p className="text-sm">{"Generate a token to enable external wake-ups. Generating a new token immediately invalidates any previous one."}</p>}
      <div className="flex flex-wrap gap-2"><Button disabled={busy} onClick={() => void act(async () => setEventToken(await api(`work/${eventWork.work_id}/event-token`, {})), eventToken ? "New token generated. The previous token no longer works." : "Event token generated. Copy it now; it will not be shown again.")}>{eventToken ? "Rotate token" : "Generate event token"}</Button><Button variant="outline" disabled={busy} onClick={() => {setEventWork(null); setEventToken(null);}}>Close</Button></div>
    </div>}</DialogContent></Dialog>
    <Dialog open={!!notesAgent} onOpenChange={v => {if (!v) setNotesAgent("");}}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>Private notes</DialogTitle><DialogDescription>Private to your account and this agent. Review, edit or delete notes. Deletion does not erase earlier run history. Shared agents do not share your notes.</DialogDescription></DialogHeader>{error && <p role="alert" className="text-destructive">{error}</p>}{notes.map(n => <div key={n.note_id} className="flex items-center justify-between gap-2 rounded-lg border p-2"><button className="text-left text-sm underline" onClick={() => setNote(n)}>{n.title}</button><Button variant="ghost" size="sm" disabled={busy} onClick={() => void act(async () => {await api(`notes/${notesAgent}/${n.note_id}`, undefined,"DELETE"); setNotes(notes.filter(x => x.note_id !== n.note_id)); if (note.note_id === n.note_id) setNote({note_id:"",title:"",content:""});}, "Note deleted; future retrievals cannot read it.")}>Delete</Button></div>)}<form className="space-y-3" onSubmit={e => {e.preventDefault(); void act(async () => {await api(`notes/${notesAgent}`, {...note,note_id:note.note_id || crypto.randomUUID()}); setNotes((await api<{notes:Note[]}>(`notes/${notesAgent}`)).notes); setNote({note_id:"",title:"",content:""});}, "Note saved");}}><Label htmlFor="note-file">Attach a playbook (.txt or .md, up to 6 KB)</Label><Input id="note-file" type="file" accept=".txt,.md" onChange={async e => {const file=e.target.files?.[0]; if (!file) return; if (file.size > 6000 || !/\.(txt|md)$/i.test(file.name)) {setError("Choose a text or Markdown file up to 6 KB."); return;} try {setNote({note_id:"", title:file.name, content:await file.text()});} catch {setError("Could not read this file. Try pasting its contents.");}}} /><Label htmlFor="note-title">Note title</Label><Input id="note-title" required value={note.title} onChange={e => setNote({...note,title:e.target.value})} /><Label htmlFor="note-content">Approved context or preference</Label><Textarea id="note-content" required maxLength={6000} rows={8} value={note.content} onChange={e => setNote({...note,content:e.target.value})} /><Button disabled={busy}>{note.note_id ? "Update note" : "Save note"}</Button></form></DialogContent></Dialog>
  </main>;
}

function ProviderCheck({approval}: {approval: Approval}) {
  const check = approval.provider_check;
  if (!check) return null;
  return <section aria-label="Gmail verification" className="my-2 rounded-lg border p-3 text-sm">
    <p className="font-medium">{check.outcome === "sent" ? "Verified in Gmail Sent" : check.outcome === "unavailable" ? "Gmail check unavailable" : "Delivery remains unconfirmed"}</p>
    <p className="mt-1 text-muted-foreground">{check.outcome === "sent" ? "Matching message found in this account’s Sent folder. This does not confirm recipient delivery. No resend or run restart." : "No conclusive provider evidence. A missing result does not mean the email was not sent. Do not resend."}</p>
    {check.checked_at && <p className="mt-1 text-xs">Checked {new Date(check.checked_at).toLocaleString()} · {check.attempts || 0}/5 automatic checks</p>}
    {check.message_id && <p className="mt-1 break-all text-xs">Gmail message ID: {check.message_id}</p>}
  </section>;
}
