// Isolated local-stack E2E. Real auth/API/DB/UI; model and external tools stubbed.
// Source dashboard/.env, then NODE_PATH=<playwright node_modules> node tests/agent-work.browser.cjs
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const { chromium } = require('playwright');
const { MongoClient } = require('mongodb');
(async () => {
  assert.match(process.env.OBSERVABILITY_DB_NAME, /^loma_local_/);
  const base = process.env.AUTH_URL;
  assert.match(base, /^http:\/\/localhost:/);
  const shots = process.env.SHOTS_DIR || '/tmp/agent-work-shots';
  fs.mkdirSync(shots, { recursive: true });
  const mongo = await new MongoClient(process.env.OBSERVABILITY_MONGODB_URI).connect();
  const db = mongo.db(process.env.OBSERVABILITY_DB_NAME);
  const browser = await chromium.launch({ headless: true });
  const errors = [];
  async function login(email) {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    page.setDefaultTimeout(20000);
    page.on('pageerror', e => errors.push(e.message));
    await page.goto(`${base}/login`, { timeout: 90000, waitUntil: 'networkidle' });
    await page.fill('#signin-email', email);
    await page.fill('#signin-password', process.env.PASSWORD);
    await page.fill('#setup-token', process.env.LOMA_SETUP_TOKEN);
    await page.click('button[type=submit]');
    await page.waitForURL(u => !u.pathname.includes('/login'), { timeout: 60000 });
    return page;
  }
  try {
    const page = await login(process.env.USER_NAME);
    await page.goto(`${base}/agents`, { timeout: 90000, waitUntil: 'networkidle' });
    // Make the isolated test safely repeatable without touching unrelated fixtures.
    const previous = await db.collection('agent_identities').find({ name: 'Meeting assistant (QA)' }).toArray();
    const ids = previous.map(a => a.agent_id);
    await db.collection('flows').deleteMany({ agent_id: { $in: ids } });
    await db.collection('agent_identities').deleteMany({ agent_id: { $in: ids } });
    await db.collection('users').deleteOne({ email: 'qa-viewer@example.com' });
    await page.reload({ waitUntil: 'networkidle' });
    await page.getByRole('button', { name: 'New agent', exact: true }).first().click();
    const dialog = page.getByRole('dialog');
    await dialog.locator('#agent-name').fill('Meeting assistant (QA)');
    await dialog.locator('#agent-description').fill('Prepares a morning brief for upcoming meetings');
    const agentResponse = page.waitForResponse(r => r.url().endsWith('/api/agent-identities') && r.request().method() === 'POST');
    await dialog.getByRole('button', { name: 'Create agent', exact: true }).click();
    const agent = (await (await agentResponse).json()).agent;
    await page.getByRole('button', { name: 'Scheduled work', exact: true }).last().click();
    await dialog.getByText('No scheduled work yet', { exact: true }).waitFor();
    await page.screenshot({ path: `${shots}/empty.png` });
    await dialog.getByRole('button', { name: 'New schedule', exact: true }).click();
    await dialog.locator('#work-name').fill('Morning meeting brief (QA)');
    await dialog.locator('#work-prompt').fill('Prepare a brief with attendees, recent context and three questions. No external messages.');
    await dialog.locator('#work-zone').fill('Invalid/Timezone');
    await dialog.getByRole('button', { name: 'Save paused schedule', exact: true }).click();
    await dialog.getByRole('alert').waitFor();
    assert.match(await dialog.getByRole('alert').innerText(), /valid timezone/);
    assert.equal(await db.collection('flows').countDocuments({ agent_id: agent.agent_id }), 0);
    await dialog.locator('#work-zone').fill('Asia/Kolkata');
    await dialog.locator('#work-frequency').focus();
    await page.keyboard.press('ArrowDown');
    await page.keyboard.press('ArrowUp');
    assert.equal(await dialog.locator('#work-frequency').inputValue(), 'weekdays');
    await page.screenshot({ path: `${shots}/desktop-create.png` });
    const savedResponse = page.waitForResponse(r => r.url().endsWith('/api/flows') && r.request().method() === 'POST');
    await dialog.getByRole('button', { name: 'Save paused schedule', exact: true }).click();
    const savedResponseValue = await savedResponse;
    assert.equal(savedResponseValue.status(), 201, await savedResponseValue.text());
    const job = (await savedResponseValue.json()).flow;
    assert.equal(job.status, 'paused');
    assert.equal(job.run_as, process.env.USER_NAME);
    assert.equal(job.visibility, 'private');
    assert.equal(job.cron, '0 9 * * 1-5');
    assert.equal(job.agent_id, agent.agent_id);
    await dialog.getByText('Schedule saved and paused.', { exact: false }).waitFor();
    await page.reload({ waitUntil: 'networkidle' });
    await page.getByRole('button', { name: 'Scheduled work', exact: true }).last().click();
    const card = dialog.getByRole('region', { name: job.name, exact: true });
    await card.getByRole('button', { name: 'Enable schedule', exact: true }).click();
    await card.getByRole('button', { name: 'Cancel', exact: true }).click();
    assert.equal((await db.collection('flows').findOne({ flow_id: job.flow_id })).status, 'paused');
    await card.getByRole('button', { name: 'Enable schedule', exact: true }).click();
    await card.getByText('Review saved agent instructions', { exact: true }).click();
    await card.getByText('## Active Agent:', { exact: false }).waitFor();
    await page.screenshot({ path: `${shots}/enable-review.png` });
    await card.getByRole('button', { name: 'Confirm & enable', exact: true }).click();
    await card.getByRole('button', { name: 'Pause schedule', exact: true }).waitFor();
    // Only the model boundary is stubbed. Run the real executor/observer on the saved job.
    const root = path.resolve(__dirname, '../..');
    const execution = spawnSync(`${root}/.venv/bin/python`, ['-c', 'import asyncio,sys;from tests.test_agent_work_local import execute_fixture;asyncio.run(execute_fixture(sys.argv[1]))', job.flow_id], { cwd: root, env: { ...process.env, LOMA_LOCAL_E2E: '1' }, encoding: 'utf8' });
    assert.equal(execution.status, 0, execution.stderr);
    const runsResponse = await page.request.get(`${base}/api/flows/${job.flow_id}/runs`);
    const runs = (await runsResponse.json()).runs;
    assert.equal(runs.length, 1);
    assert.equal(runs[0].metadata.agent_id, agent.agent_id);
    assert.equal(runs[0].metadata.run_as, process.env.USER_NAME);
    await dialog.getByRole('button', { name: 'Refresh', exact: true }).click();
    await card.getByText('1 completed run', { exact: false }).waitFor();
    await page.screenshot({ path: `${shots}/completed-run.png` });
    await card.getByRole('link', { name: 'Details & run history', exact: true }).click();
    await page.waitForURL(`**/flows/${job.flow_id}`);
    await page.getByText('Morning meeting brief (QA)', { exact: true }).first().waitFor();
    await page.getByRole('region', { name: 'Pinned agent' }).waitFor();
    assert.equal(await page.getByRole('combobox', { name: 'Execution account', exact: true }).count(), 0);
    assert.equal(await page.getByRole('button', { name: 'Private', exact: true }).count(), 0);
    await page.getByText('View saved agent instructions', { exact: true }).click();
    await page.screenshot({ path: `${shots}/run-history.png` });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForTimeout(700); // Wait for the shell's responsive sidebar transition.
    await page.screenshot({ path: `${shots}/mobile-details.png`, fullPage: true });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Mobile details page overflow');
    await page.getByText('Execution History', { exact: true }).scrollIntoViewIfNeeded();
    const historyBottom = (await page.getByText('Execution History', { exact: true }).boundingBox()).y;
    const navTop = (await page.getByRole('navigation').filter({ has: page.getByRole('link', { name: 'Usage', exact: true }) }).boundingBox()).y;
    assert(historyBottom < navTop, 'Run history is hidden behind the bottom navigation');
    await page.screenshot({ path: `${shots}/mobile-history.png` });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.getByRole('link', { name: 'Manage agent schedules', exact: true }).click();
    await dialog.getByRole('region', { name: job.name, exact: true }).waitFor();
    await card.getByRole('button', { name: 'Pause schedule', exact: true }).click();
    await card.getByRole('button', { name: 'Enable schedule', exact: true }).waitFor();
    // Revoke the execution account after the schedule was saved. Real backend rejection.
    await db.collection('users').updateOne({ email: process.env.USER_NAME }, { $set: { status: 'inactive' } });
    await card.getByRole('button', { name: 'Enable schedule', exact: true }).click();
    await card.getByRole('button', { name: 'Confirm & enable', exact: true }).click();
    await dialog.getByRole('alert').waitFor();
    assert.match(await dialog.getByRole('alert').innerText(), /inactive/);
    await db.collection('users').updateOne({ email: process.env.USER_NAME }, { $set: { status: 'active' } });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForTimeout(700);
    await page.screenshot({ path: `${shots}/mobile-error.png` });
    assert(await dialog.evaluate(e => e.scrollWidth <= e.clientWidth), 'Mobile dialog overflow');
    await card.getByRole('button', { name: 'Cancel', exact: true }).click();
    await dialog.getByRole('button', { name: 'New schedule', exact: true }).click();
    await dialog.locator('#work-name').fill('Cancelled draft');
    await page.screenshot({ path: `${shots}/mobile-create.png` });
    assert(await dialog.evaluate(e => e.scrollWidth <= e.clientWidth), 'Mobile form overflow');
    await dialog.getByRole('button', { name: 'Cancel', exact: true }).click();
    assert.equal(await db.collection('flows').countDocuments({ agent_id: agent.agent_id }), 1);
    // Sharing the agent does not share its owner's schedules or execution account.
    await db.collection('agent_identities').updateOne({ agent_id: agent.agent_id }, { $set: { visibility: 'workspace' } });
    const admin = await db.collection('users').findOne({ email: process.env.USER_NAME });
    await db.collection('users').insertOne({ email: 'qa-viewer@example.com', name: 'QA viewer', system_role: 'analyst', status: 'active', local_auth: admin.local_auth });
    const viewer = await login('qa-viewer@example.com');
    await viewer.goto(`${base}/agents`, { waitUntil: 'networkidle' });
    await viewer.getByRole('button', { name: 'Scheduled work', exact: true }).click();
    await viewer.getByRole('dialog').getByText('No scheduled work yet', { exact: true }).waitFor();
    assert.equal(await viewer.getByRole('button', { name: 'New schedule', exact: true }).count(), 0);
    assert.equal((await viewer.request.get(`${base}/api/flows/${job.flow_id}`)).status(), 404);
    assert.equal((await viewer.request.get(`${base}/api/flows/${job.flow_id}/runs`)).status(), 404);
    // A failed fetch is not an empty schedule list. Refresh recovers without a reload.
    await viewer.getByRole('dialog').getByRole('button', { name: 'Close', exact: true }).click();
    await viewer.route('**/api/flows?*', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"error":"Temporarily unavailable"}' }));
    await viewer.getByRole('button', { name: 'Scheduled work', exact: true }).click();
    await viewer.getByRole('dialog').getByText('Schedules could not be loaded. Use Refresh to try again.').waitFor();
    assert.equal(await viewer.getByText('No scheduled work yet', { exact: true }).count(), 0);
    await viewer.unroute('**/api/flows?*');
    await viewer.getByRole('dialog').getByRole('button', { name: 'Refresh', exact: true }).click();
    await viewer.getByText('No scheduled work yet', { exact: true }).waitFor();
    await viewer.screenshot({ path: `${shots}/private-work.png` });
    assert.deepEqual(errors, []);
    console.log('PASS: agent creation, schedule save/reload, timezone validation, keyboard, cancel, explicit enable, stubbed execution with real run history, pause, revoked-account rejection, mobile layouts, private work isolation, no browser errors.');
  } finally {
    await db.collection('users').updateOne({ email: process.env.USER_NAME }, { $set: { status: 'active' } });
    await browser.close(); await mongo.close();
  }
})().catch(e => { console.error(e); process.exit(1); });
